da.API.CreateUseableItem("canteen", function(source, item)
    TriggerClientEvent("da_xanims:queueAnim", source, "drink_canteen", "enter", item)
end)

da.API.CreateUseableItem("apple", function(source, item)
    TriggerClientEvent("da_xanims:queueAnim", source, "eat_apple", "enter", item)
end)

da.API.CreateUseableItem("pear", function(source, item)
    TriggerClientEvent("da_xanims:queueAnim", source, "eat_pear", "enter", item)
end)

da.API.CreateUseableItem("bread", function(source, item)
    TriggerClientEvent("da_xanims:queueAnim", source, "eat_breadroll", "enter", item)
end)

local GenericFood = {
    eat_generic = {
        alaskanginseng = { amount = 5, },
        americanginseng = { amount = 5, },
        animalfat = { amount = 5, },
        applefritters = { amount = 25, },
        applesnow = { amount = 20, },
        assortedbiscuits = { amount = 20, },
        bacon = { amount = 25, },
        bakedpotato = { amount = 15, },
        baybolete = { amount = 5, },
        cookedbeavertail = { amount = 25, },
        blackberry = { amount = 5, },
        blackcurrant = { amount = 5, },
        blackcurrantjam = { amount = 5, },
        brandyball = { amount = 15, },
        bulrush = { amount = 5, },
        burdock = { amount = 5, },
        butter = { amount = 5, },
        butteredpopcorn = { amount = 10, },
        candies = { amount = 5, },
        candiedoranges = { amount = 15, },
        candycane = { amount = 5, },
        carrotcake = { amount = 15, },
        chanterelles = { amount = 5, },
        cheese = { amount = 15, },
        cheesewedge = { amount = 15, },
        chocolate = { amount = 10, },
        chocolatebar = { amount = 10, },
        christmaspudding = { amount = 25, },
        cidercake = { amount = 25, },
        classicoatcakes = { amount = 15, },
        cookedbiggamemeat = { amount = 25, },
        cookedbirdmeat = { amount = 25, },
        cookedcrustaceanmeat = { amount = 25, },
        cookedgristlymutton = { amount = 25, },
        cookedherptilemeat = { amount = 25, },
        cookedmaturevenison = { amount = 25, },
        cookedprimebeefjoint = { amount = 25, },
        cookedplumpbird = { amount = 25, },
        cookedprimebeef = { amount = 25, },
        cookedstringymeat = { amount = 25, },
        cookedtenderporkloin = { amount = 25, },
        cookedgamemeat = { amount = 25, },
        cookedfish = { amount = 25, },
        cornbread = { amount = 10, },
        cornishpasty = { amount = 25, },
        crabcakes = { amount = 25, },
        crackers = { amount = 10, },
        desertsage = { amount = 5, },
        doughnut = { amount = 20, },
        egg = { amount = 10, },
        electioncake = { amount = 35, },
        emptypudding = { amount = 15, },
        englishmace = { amount = 5, },
        evergreenhuckleberry = { amount = 5, },
        fennel = { amount = 5, },
        feverfew = { amount = 5, },
        fishcake = { amount = 20, },
        friedbatwing = { amount = 5, },
        friedgreentomatoes = { amount = 20, },
        fruitcake = { amount = 30, },
        frybread = { amount =  25, },
        gingerbread = { amount = 10, },
        goldencurrant = { amount = 5, },
        granoseflakes = { amount = 25, },
        grapes = { amount = 10, },
        hamburger = { amount = 25, },
        hardtack = { amount = 25, },
        herptilemeat = { amount = 10, },
        honey = { amount = 25, },
        hotdog = { amount = 25, },
        huckleberryjam = { amount = 5, },
        hummingbirdsage = { amount = 5, },
        indiantobacco = { amount = 5, },
        jamontoast = { amount = 10, },
        jarofcherries = { amount = 15, },
        jerky = { amount = 20, },
        johnnycake = { amount = 15, },
        lemoncake = { amount = 15, },
        lime = { amount = 5, },
        macncheese = { amount = 25, },
        maggotsandwich = { amount = 1, },
        marmalade = { amount = 15, },
        marmaladetoast = { amount = 30, },
        milkweed = { amount = 5, },
        mincepie = { amount = 35, },
        molassescookie = { amount = 5, },
        mushroom = { amount = 5, },
        oregano = { amount = 5, },
        orleander = { amount = 5, },
        paynperdu = { amount = 25, },
        parasol = { amount = 5, },
        peanuts = { amount = 5, },
        pear = { amount = 15, },
        pemmican = { amount = 30, },
        pickle = { amount = 10, },
        pickeledeggs = { amount = 15, },
        popcorn = { amount = 10, },
        popcornballs = { amount = 15, },
        potashcake = { amount = 15, },
        potatosnow = { amount = 20, },
        prariepoppy = { amount = 5, },
        ramshead = { amount = 5, },
        raspberry = { amount = 5, },
        raspberryjam = { amount = 5, },
        raspberrypie = { amount = 15, },
        redsage = { amount = 5, },
        redwillowbark = { amount = 5, }, -- Health Increase if possible?
        ricecake = { amount = 15, },
        roast = { amount = 40, },
        sallylunnbuns = { amount = 15, },
        saltedbeef = { amount = 25, },
        sausage = { amount = 25, },
        shepherdspie = { amount = 35, },
        shipsbiscuit = { amount = 15, },
        slosh = { amount = 25, },
        spicedgrape = { amount = 10, },
        spicedmeat = { amount = 15, },
        steamedbuns = { amount = 30, },
        sugar = { amount = 5, },
        sugarcube = { amount = 5, },
        tavernbiscuit = { amount = 25, },
        teaegg = { amount = 15, },
        thyme = { amount = 5, },
        toast = { amount = 10, },
        toastsandwich = { amount = 30, },
        tomatotoast = { amount = 20, },
        vanilla = { amount = 5, },
        vanillaflower = { amount = 5, },
        violetsnowdrop = { amount = 5, },
        wildcarrot = { amount = 5, },
        wildmint = { amount = 5, },
        wintergreen = { amount = 5, },
        wolfheart = { amount = 5, },
        yarrow = { amount = 5, },
    },
    eat_generic_can = {
        assortedsaltedoffal = { amount = 15, },
        bakedbeans = { amount = 20, },
        cannedapricots = { amount = 20, },
        cannedcornedbeef = { amount = 25, },
        cannedkidneybeans = { amount = 25, },
        cannedpeaches = { amount = 20, },
        cannedpeas = { amount = 15, },
        cannedpineapple = { amount = 20, },
        cannedsalmon = { amount = 25, },
        cannedstrawberries = { amount = 20, },
        cannedsweetcorn = { amount = 15, },
    },
    eat_generic_stew = {
        batsoup = { amount = 15, propset = "Bisque" },
        beefstew = { amount = 30, },
        blackberrybuckle = { amount = 15, },
        chickengumbo = { amount = 25, propset = "FishStew"},
        cornedbeefhash = { amount = 30, },
        escallopedpotatoes = { amount = 25, propset = "Cobbler" },
        friedapples = { amount = 25, propset = "Cobbler" },
        friedfowl = { amount = 35, },
        jelliedeel = { amount = 35, },
        lambstew = { amount = 40, },
        lobscouse = { amount = 40, propset = "Bisque" },
        norfolkdumpling = { amount = 25, },
        scrambledegg = { amount = 40, "Cobbler" },
        spaghetti = { amount = 35, },
        stew = { amount = 15, },
        stobhachgaedhealach = { amount = 35, },
        succotash = { amount = 25, },
        texaschili = { amount = 40, },
        tomatosoup = { amount = 25, propest = "Cabbage" },
        turkeydinner = { amount = 50, },
        varmintstew = { amount = 25, },

        guarmasalad = { amount = 20, propset = "Cabbage"},

        porridge = { amount = 25, propset = "Porridge", },

        applecobbler = { amount = 15, propset = "Cobbler", },
        peachbrownbetty = { amount = 15, propset = "Cobbler", },
        pumpkinpie = { amount = 15, propset = "Cobbler"},
        pumpkinseeds = { amount = 15, propset = "Cobbler"},

        stuffedbakedfish = { amount = 40, propset = "FishStew", },

    },
}

for animLibName, foodTypeData in pairs(GenericFood) do
    for itemName, foodData in pairs(foodTypeData) do
        da.API.CreateUseableItem(itemName, function(source, item)
            item.increaseAmount = foodData.amount
            item.propset = foodData.propset
            TriggerClientEvent("da_xanims:queueAnim", source, animLibName, "enter", item)
        end)
    end
end
